# Generated by Django 4.1.4 on 2023-01-26 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("file", models.FileField(upload_to="files/")),
                (
                    "access_control",
                    models.IntegerField(
                        choices=[(0, "Public"), (1, "Student"), (2, "TA"), (3, "Admin")]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("employee_id", models.IntegerField()),
                ("academic_email", models.EmailField(max_length=254)),
                ("github_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="media/TAs/images")),
            ],
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "semester",
                    models.IntegerField(
                        choices=[(1, "Fall"), (2, "Spring"), (3, "Summer")]
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("subtitle", models.TextField()),
                ("description", models.TextField()),
            ],
            options={
                "ordering": ["-year", "semester"],
                "unique_together": {("year", "semester")},
            },
        ),
        migrations.CreateModel(
            name="URLMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("subtitle", models.TextField()),
                ("description", models.TextField()),
                (
                    "files",
                    models.ManyToManyField(
                        blank=True,
                        related_name="session_files",
                        to="course.filematerial",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.semester",
                    ),
                ),
                (
                    "urls",
                    models.ManyToManyField(
                        blank=True, related_name="session_urls", to="course.urlmaterial"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="filematerial",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="course.semester"
            ),
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("subtitle", models.TextField()),
                ("description", models.TextField()),
                (
                    "files",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assignment_files",
                        to="course.filematerial",
                    ),
                ),
                (
                    "questions",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="questions",
                        to="course.filematerial",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.semester",
                    ),
                ),
                (
                    "solutions",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="solutions",
                        to="course.filematerial",
                    ),
                ),
                (
                    "urls",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assignment_urls",
                        to="course.urlmaterial",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeachingAssisting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.person"
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.semester",
                    ),
                ),
            ],
            options={
                "unique_together": {("person", "semester")},
            },
        ),
        migrations.CreateModel(
            name="Instruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.person"
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.semester",
                    ),
                ),
            ],
            options={
                "unique_together": {("person", "semester")},
            },
        ),
        migrations.CreateModel(
            name="Enrolling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.person"
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.semester",
                    ),
                ),
            ],
            options={
                "unique_together": {("person", "semester")},
            },
        ),
    ]
