# Generated by Django 4.1.5 on 2023-01-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_semester_syllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, upload_to='TAs/images'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='syllabus',
            field=models.FileField(blank=True, upload_to='syllabus'),
        ),
    ]
